AWSTemplateFormatVersion: '2010-09-09'
Description: Cognito User Pool for ShopFast Auth

Resources:
  ShopFastUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: shopfast-auth
      AutoVerifiedAttributes:
        - email

  ShopFastResourceServer:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties:
      Identifier: payment-service
      Name: Payment Service
      UserPoolId: !Ref ShopFastUserPool
      Scopes:
        - ScopeName: payments.create
          ScopeDescription: Create payments
        - ScopeName: payments.refund
          ScopeDescription: Refund payments

  ShopFastUserPoolClientA:
    Type: AWS::Cognito::UserPoolClient
    DependsOn: ShopFastResourceServer
    Properties:
      ClientName: client_a
      UserPoolId: !Ref ShopFastUserPool
      GenerateSecret: true
      AllowedOAuthFlows:
        - client_credentials
      AllowedOAuthScopes:
        - payment-service/payments.create
        - payment-service/payments.refund
      AllowedOAuthFlowsUserPoolClient: true
      
Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref ShopFastUserPool
    Export:
      Name: ShopFast-UserPoolId

  UserPoolArn:
    Description: Cognito User Pool ARN
    Value: !GetAtt ShopFastUserPool.Arn
    Export:
      Name: ShopFast-UserPoolArn

  UserPoolClientId:
    Description: Cognito App Client ID A
    Value: !Ref ShopFastUserPoolClientA
    Export:
      Name: ShopFast-UserPoolClientId

  ResourceServerIdentifier:
    Description: Cognito Resource Server Identifier
    Value: payment-service
    Export:
      Name: ShopFast-ResourceServerIdentifier
