AWSTemplateFormatVersion: '2010-09-09'
Description: Cognito User Pool with OAuth2 Client Credentials for ShopFast

Resources:

  # ------------------------------------------------------------
  # Cognito User Pool
  # ------------------------------------------------------------
  ShopFastUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: shopfast-auth
      AutoVerifiedAttributes:
        - email

  # ------------------------------------------------------------
  # Cognito Resource Server (Custom Scopes)
  # ------------------------------------------------------------
  ShopFastResourceServer:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties:
      Identifier: payment-service
      Name: Payment Service
      UserPoolId: !Ref ShopFastUserPool
      Scopes:
        - ScopeName: payments.create
          ScopeDescription: Create payments
        - ScopeName: payments.refund
          ScopeDescription: Refund payments

  # ------------------------------------------------------------
  # Cognito App Client (Client Credentials Flow)
  # ------------------------------------------------------------
  ShopFastUserPoolClientA:
    Type: AWS::Cognito::UserPoolClient
    DependsOn: ShopFastResourceServer
    Properties:
      ClientName: client-a
      UserPoolId: !Ref ShopFastUserPool
      GenerateSecret: true
      AllowedOAuthFlows:
        - client_credentials
      AllowedOAuthScopes:
        - payment-service/payments.create
        - payment-service/payments.refund
      AllowedOAuthFlowsUserPoolClient: true
      SupportedIdentityProviders:
        - COGNITO

      # Explicitly disable user-based auth flows
      ExplicitAuthFlows: []

  # ------------------------------------------------------------
  # Cognito Hosted Domain (REQUIRED for OAuth2)
  # ------------------------------------------------------------
  ShopFastUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: denil-shopfast
      UserPoolId: !Ref ShopFastUserPool

Outputs:

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref ShopFastUserPool
    Export:
      Name: ShopFast-UserPoolId

  UserPoolArn:
    Description: Cognito User Pool ARN
    Value: !GetAtt ShopFastUserPool.Arn
    Export:
      Name: ShopFast-UserPoolArn

  UserPoolClientId:
    Description: Cognito App Client ID
    Value: !Ref ShopFastUserPoolClientA
    Export:
      Name: ShopFast-UserPoolClientIdA

  ResourceServerIdentifier:
    Description: Cognito Resource Server Identifier
    Value: payment-service
    Export:
      Name: ShopFast-ResourceServerIdentifier

  CognitoDomain:
    Description: Cognito Hosted Domain
    Value: !Sub "https://${ShopFastUserPoolDomain}.auth.${AWS::Region}.amazoncognito.com"
    Export:
      Name: ShopFast-AuthDomain
